language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

branches:
  except:
    - /^v1\.\d+/

before_install:
- composer require --dev codeclimate/php-test-reporter

before_script:
- mkdir -p build/logs

script:
- vendor/bin/phpunit

after_script:
- php vendor/bin/test-reporter
